version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  server:
    image: danilnovikovdev/server:1.0.0
    build: .
    restart: always
    depends_on:
      - "postgres"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dockerapi-dev

  postgres:  
    image: postgres:13.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"      
      POSTGRES_PASSWORD: "pricer"
      POSTGRES_DB: "PricerDB"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dockerapi-dev  